'use strict';
// Measurements live on the same recording object as audio and feelings.
const analysisJobs=new Map();
const BALANCE_BASIS='tilt-corrected-band-rms-v1';
const VOICE_STATUS={quiet:'30cm 거리를 유지하고, 소리를 조금 더 크게 내보세요.',clipped:'30cm 거리를 유지하고, 힘을 빼고 조금 작게 말해보세요.',short:'목소리가 짧아요. 3초 이상 편하게 읽어주세요.',uncertain:'또렷하게 들린 구간이 부족해요. 조용한 곳에서 다시 읽어주세요.'};
function hz(value){return Number.isFinite(value)?Math.round(value).toLocaleString('ko-KR'):'—';}
function voiceNote(value){if(!Number.isFinite(value)||value<=0)return '';const midi=Math.round(69+12*Math.log2(value/440));return ['도','도♯','레','레♯','미','파','파♯','솔','솔♯','라','라♯','시'][(midi%12+12)%12]+(Math.floor(midi/12)-1);}
function voiceSummary(r){if(r?.metrics?.status==='ready')return hz(r.metrics.pitchMean)+' Hz'+(r.pace?.status==='ready'?' · '+r.pace.syllablesPerSecond.toFixed(1)+'음절/초':'');return analysisJobs.has(r?.id)?'분석 중':r?.metrics?'다시 확인':'녹음 분석';}
function pitchComparison(value){if(!Number.isFinite(value))return '';const rel=ref=>Math.abs(value-ref)<10?'비슷해요':value>ref?'높아요':'낮아요';return `남성 평균보다 ${rel(120.8)} · 여성 평균보다 ${rel(217.1)}`.replaceAll('보다 비슷해요','과 비슷해요');}
function pitchScale(m){const position=v=>Math.max(0,Math.min(100,Math.log2(Math.max(60,v)/60)/Math.log2(500/60)*100));return `<div class="pitch-scale" role="img" aria-label="목소리 높이: 나 ${hz(m.pitchMean)} Hz, 남성 참고 평균 121 Hz, 여성 참고 평균 217 Hz"><div class="pitch-track"><i class="pitch-own-range" style="left:${position(m.pitchRange.low)}%;width:${position(m.pitchRange.high)-position(m.pitchRange.low)}%"></i><b class="pitch-reference male" style="left:${position(120.8)}%"><span>남성<small>121 Hz</small></span></b><b class="pitch-reference female" style="left:${position(217.1)}%"><span>여성<small>217 Hz</small></span></b><b class="pitch-self" style="left:${position(m.pitchMean)}%"><span>나</span></b></div><div class="pitch-axis"><span>60 Hz</span><span>500 Hz</span></div></div><p class="pitch-range-copy">자주 낸 음 ${hz(m.pitchRange.low)}–${hz(m.pitchRange.high)} Hz</p>`;}
function goalSettings(){const saved=localGet('sq-voice-goal',{});return {kind:saved?.kind==='trust'?'trust':'friendly',hz:Number.isFinite(saved?.hz)&&saved.hz>=65&&saved.hz<=450?saved.hz:null};}
function goalMarkup(m){const g=goalSettings(),base=g.hz,label=g.kind==='trust'?'신뢰감 있는 말투':'친절한 말투';return `<div class="voice-goal"><div class="metric-title"><h3>목소리 목표</h3><button class="quiet-link" data-action="voice-goal">설정</button></div><strong>${base?`${label} · ${hz(base/2**(2/12))}–${hz(base*2**(2/12))} Hz`:'내가 편한 높이부터'}</strong><p>${base?(g.kind==='trust'?'서두르지 않고, 말끝을 또렷하게.':'부드럽게 시작하고, 말에 표정을 담아요.'):'친절함과 신뢰감에는 정해진 Hz가 없어요.'}</p>${base?'<small>내가 고른 높이의 연습 범위</small>':''}</div>`;}
function paceMarkup(r){const p=r.pace,working=analysisJobs.has(r.id);if(p?.status==='offline')return '<div class="metric-title"><h3>말의 빠르기 · 울림</h3></div><p>정밀 분석에 연결하면 확인할 수 있어요.</p><button class="quiet-link" data-action="connect-analysis">연결하기</button>';if(p?.status==='ready'){return `<div class="metric-title"><h3>말의 빠르기</h3><strong>${p.syllablesPerSecond.toFixed(1)} <small>음절/초</small></strong></div><div class="pace-options"><span class="${p.pace==='slow'?'active':''}">천천히</span><span class="${p.pace==='within'?'active':''}">연습 범위</span><span class="${p.pace==='fast'?'active':''}">빠르게</span></div><p>${p.pace==='fast'?'문장 사이에 한 박자 쉬어보세요.':p.pace==='slow'?'뜻이 이어지는 말은 조금 더 연결해보세요.':'지금은 연습 범위 안이에요.'}</p><small>연습 기준 3–5음절/초 · 인식 오차가 있을 수 있어요</small><details class="voice-note"><summary>인식한 말</summary><p>${esc(p.transcript)}</p><small>${p.syllables}음절 / ${p.seconds.toFixed(1)}초 · 중간 쉼 포함</small></details>`;}
return `<div class="metric-title"><h3>말의 빠르기</h3><strong>—</strong></div><p>${working?'말을 인식하고 있어요. 먼저 들어도 좋아요.':p?.status==='unavailable'?'말 인식 모델을 불러오지 못했어요.':p?.status==='loading'?'말 인식 모델을 준비 중이에요.':p?.status==='busy'?'다른 녹음을 분석 중이에요. 잠시 후 다시 눌러주세요.':p?.status==='uncertain'?'인식한 말이 부족해 빠르기를 계산하지 않았어요.':'말의 빠르기를 다시 확인할 수 있어요.'}</p>${!working?`<button class="quiet-link" data-analyze="${esc(r.id)}" data-pace-only="true">빠르기 다시 확인</button>`:''}`;}
function voiceImage(m){
 const fs=m?.formants;if(!fs||fs.length<3||!fs.every(Number.isFinite)||!(fs[0]<fs[1]&&fs[1]<fs[2]))return {label:'울림을 더 살펴볼게요',copy:'다음 문장을 편하게 읽어주세요.'};
 // A provisional timbre description, not a personality or listener-impression classifier.
 const spread=(fs[2]-fs[0])/2;
 return spread<1100?{label:'묵직한 울림',copy:'낮고 넓은 울림으로 들릴 수 있어요.'}:spread>1450?{label:'밝은 울림',copy:'가볍고 밝은 울림으로 들릴 수 있어요.'}:{label:'담백한 울림',copy:'중간 톤의 담백한 울림으로 들릴 수 있어요.'};
}
function levelMarkup(m){const level=m?.level;if(!level)return '';const labels={soft:'조금 더 크게',usable:'잘 담겼어요',loud:'조금 더 편하게',clipped:'소리를 줄여주세요'};let guide=level.state==='soft'?'30cm 거리를 유지하고, 소리를 조금 더 크게 내보세요.':level.state==='clipped'||level.state==='loud'?'30cm 거리를 유지하고, 힘을 빼고 조금 작게 말해보세요.':level.span==='narrow'?'중요한 말을 조금 더 크게, 편하게 읽어보세요.':'지금 크기로 편하게 읽어주세요.';return `<div class="voice-metric"><div class="metric-title"><h3>소리 크기 · 강약</h3><span class="metric-word">${labels[level.state]||'확인 중'}</span></div>${level.span?`<div class="range-options"><span class="${level.span==='narrow'?'active':''}">강약이 작아요</span><span class="${level.span==='varied'?'active':''}">강약이 있어요</span></div>`:''}<p>${guide}</p><small>같은 30cm 거리에서 비교해요.</small></div>`;}
function stabilityLabel(m){if(Number.isFinite(m?.regularity))return m.regularity>=.92?'안정 쪽':m.regularity<.8?'흔들림 쪽':'중간';return !Number.isFinite(m?.hnr)?'—':m.hnr>18?'안정 쪽':m.hnr<11?'흔들림 쪽':'중간';}
function stabilityMarkup(m){const device=Number.isFinite(m?.regularity);if(!device&&!Number.isFinite(m?.hnr))return '';const position=Math.max(0,Math.min(100,device?(1-m.regularity)/.4*100:(25-m.hnr)/20*100)),label=stabilityLabel(m);return `<div class="voice-metric"><div class="metric-title"><h3>소리 안정감</h3><span class="metric-word">${label}</span></div><div class="stability-track" role="img" aria-label="소리 안정감: ${label}"><i style="left:${position}%"></i></div><div class="stability-labels"><span>안정</span><span>흔들림</span></div><small>소리 반복의 규칙성을 보는 연습용 표시예요.</small></div>`;}

function balanceMarkup(r){const b=r.metrics?.balance,working=analysisJobs.has(r.id),old=r.metrics?.version<3||b&&b.basis!==BALANCE_BASIS;let html='<div class="voice-metric"><div class="metric-title"><h3>저음 · 중음 · 고음</h3><small>보정된 대역 비중</small></div>';
 if(old)return html+`<p>${working?'새 기준으로 살펴보고 있어요.':r.analysisError?'분석에 연결하지 못했어요. 다시 눌러주세요.':'저음에 몰리던 계산 기준을 바꿨어요.'}</p>${working?'':`<button class="secondary" data-analyze="${esc(r.id)}" data-acoustic-only="true">새 기준으로 보기</button>`}</div>`;
 if(!b)return html+'<p>비율을 읽을 만큼 또렷한 구간이 부족해요.</p><small>같은 휴대폰·30cm 거리에서 다시 읽어주세요.</small></div>';
 html+=`<div class="balance-track" aria-hidden="true">${b.percent.map((v,i)=>`<i class="band-${i}" style="flex:${v}"></i>`).join('')}</div><div class="balance-labels">${['저음','중음','고음'].map((name,i)=>`<div><span>${name}</span><strong>${b.percent[i]}<small>%</small></strong><small>(${b.bandsHz[i][0].toLocaleString('ko-KR')}–${b.bandsHz[i][1].toLocaleString('ko-KR')} Hz)</small></div>`).join('')}</div><p>같은 휴대폰·30cm 거리에서 비교해요.</p><small>비교용 비중이에요. 세 수치를 같게 맞출 필요는 없어요.</small></div>`;return html;}
function voiceDetails(r){const m=r.metrics,ready=m?.status==='ready',working=analysisJobs.has(r.id);let content='';
 if(ready){const image=voiceImage(m);content=`${m.method==='device'?'<p class="tiny">기기 분석</p>':''}${m.formants?`<div class="voice-metric voice-image"><small>울림으로 본 참고 이미지</small><h3>${image.label}</h3><p>${image.copy}</p><small>읽은 모음과 녹음 환경에 따라 달라져요.</small></div>`:''}<div class="voice-metric"><div class="metric-title"><h3>목소리 높이</h3><strong>${hz(m.pitchMean)} <small>Hz · ${voiceNote(m.pitchMean)}</small></strong></div>${pitchScale(m)}<p>${pitchComparison(m.pitchMean)}</p><small>남성·여성 표시는 연구 평균 · 맞춰야 할 높이는 아니에요</small></div>${balanceMarkup(r)}${levelMarkup(m)}${stabilityMarkup(m)}<div class="voice-metric">${paceMarkup(r)}</div>`;}
 else content=`<div class="voice-metric"><p role="status">${working?'목소리를 분석하고 있어요.':m?VOICE_STATUS[m.status]||'분석을 다시 시도해 주세요.':r.analysisError?'분석에 연결하지 못했어요. 녹음은 그대로 남아 있어요.':'이 녹음의 높이와 음역대를 확인해요.'}</p>${!working?`<button class="secondary" data-analyze="${esc(r.id)}">${m?'다시 분석':'목소리 분석'}</button>`:''}</div>`;
 content+=goalMarkup(m);
 return content+`<button class="quiet-link method-link" data-action="voice-method">측정 기준</button>${r.unsaved?'<p class="storage-warning">분석 결과를 기기에 저장하지 못했어요. 음성은 내려받을 수 있어요.</p>':''}`;
}
function voiceMount(r){if(!r)return '';return `<div class="voice-mount" data-voice-record="${esc(r.id)}"><details class="voice-panel" ${view==='playback'?'open':''}><summary><span>내 목소리</span><span class="voice-summary">${voiceSummary(r)}</span><span class="disclosure" aria-hidden="true">＋</span></summary><div class="voice-body">${voiceDetails(r)}</div></details></div>`;}
function refreshVoice(r){document.querySelectorAll('[data-voice-record]').forEach(el=>{if(el.dataset.voiceRecord!==r.id)return;const details=el.querySelector('details'),wasOpen=details.open;const hadFocus=el.querySelector('.voice-body').contains(document.activeElement),innerOpen=[...el.querySelectorAll('.voice-note')].map(x=>x.open);el.querySelector('.voice-summary').textContent=voiceSummary(r);el.querySelector('.voice-body').innerHTML=voiceDetails(r);el.querySelectorAll('.voice-note').forEach((x,i)=>x.open=!!innerOpen[i]);details.open=wasOpen;if(hadFocus)details.querySelector('summary').focus({preventScroll:true});});
 document.querySelectorAll('[data-practice-record]').forEach(el=>{const record=records.find(x=>x.id===el.dataset.practiceRecord);if(record&&(record.id===r.id||record.practice?.baselineId===r.id)){const live=el.querySelector('.comparison-live'),focus=(live||el).contains(document.activeElement),html=practiceContent(record);if(live){const next=document.createElement('template');next.innerHTML=html;const updated=next.content.querySelector('.comparison-live');if(updated)live.innerHTML=updated.innerHTML;else el.innerHTML=html;}else el.innerHTML=html;if(focus)el.focus({preventScroll:true});}});Water.refresh();}

// Short practice suggestions use observed sound, never infer anatomy or diagnose health.
function coachAdvice(r,goal=goalSettings()){
 const m=r.metrics,tips=[];const add=(finding,action)=>tips.push({finding,action});
 if(m?.status!=='ready')return [{finding:'목소리를 한 번 더 담아볼까요?',action:VOICE_STATUS[m?.status]||'같은 문장을 편하게 끝까지 읽어주세요.'}];
 if(m.level?.state==='soft')add('소리가 작게 담겼어요','30cm를 유지하고, 지금보다 조금 더 크게 읽어보세요.');
 else if(['clipped','loud'].includes(m.level?.state))add('소리가 크게 담겼어요','30cm를 유지하고, 조금 작고 편하게 읽어보세요.');
 if(r.pace?.status==='ready'&&r.pace.pace==='fast')add('말이 조금 빨라요','쉼표에서 한 박자 쉬고, 마지막 말까지 또렷하게.');
 else if(r.pace?.status==='ready'&&r.pace.pace==='slow')add('말이 조금 느려요','뜻이 이어지는 말은 한 덩어리로 읽어보세요.');
 if(goal.hz&&classifyPitch(m.pitchMean,goal.hz)!=='match')add(`정한 높이보다 ${m.pitchMean>goal.hz?'높아요':'낮아요'}`,`기준음 ${hz(goal.hz)} Hz를 듣고, 편한 만큼 ${m.pitchMean>goal.hz?'낮춰':'높여'} 읽어보세요.`);
 if((Number.isFinite(m.regularity)&&m.regularity<.8)||(Number.isFinite(m.hnr)&&m.hnr<11))add('소리가 고르지 않게 담겼어요','조용한 곳에서, 문장 끝까지 비슷한 크기로 읽어보세요.');
 if(m.level?.span==='narrow')add('소리 크기의 변화가 작아요','중요한 단어 하나를 골라 조금 더 힘을 실어보세요.');
 const b=m.balance;if(b?.basis===BALANCE_BASIS&&Math.max(...b.percent)>=60){const i=b.percent.indexOf(Math.max(...b.percent));add(`${['저음','중음','고음'][i]} 쪽 비중이 커요`,['가볍게 “음—” 하고, 말끝까지 또렷하게 읽어보세요.','중요한 단어에 표정을 담아, 높낮이를 조금 바꿔보세요.','첫 말을 조금 낮고 편하게 시작해보세요.'][i]);}
 if(!tips.length)add('지금 흐름을 유지해요','중요한 단어 하나에 뜻을 담아 다시 읽어보세요.');
 return tips.slice(0,2);
}
function baselineFor(r){const first=records.find(x=>x.id===r.practice?.baselineId);return first&&first.id!==r.id&&first.sentenceId===r.sentenceId&&first.text===r.text?first:null;}
function deltaLabel(a,b,unit='',digits=0){if(!Number.isFinite(a)||!Number.isFinite(b))return '—';const d=Number((Number(b.toFixed(digits))-Number(a.toFixed(digits))).toFixed(digits));return d===0?'같음':`${d>0?'+':'−'}${Math.abs(d).toFixed(digits)}${unit}`;}
function comparisonRows(first,last){
 const sameEngine=(first.metrics?.comparisonKey||'praat-v3')===(last.metrics?.comparisonKey||'praat-v3');
 const a=first.metrics?.status==='ready'?first.metrics:null,b=last.metrics?.status==='ready'?last.metrics:null;
 const rows=[{label:'목소리 높이',a:a?hz(a.pitchMean)+' Hz':'—',b:b?hz(b.pitchMean)+' Hz':'—',change:sameEngine?deltaLabel(a?.pitchMean,b?.pitchMean,' Hz'):'기준 다름'}];
 const aBands=a?.balance?.basis===BALANCE_BASIS,bBands=b?.balance?.basis===BALANCE_BASIS,sameBasis=aBands&&bBands&&sameEngine;
 ['저음','중음','고음'].forEach((label,i)=>rows.push({label,band:i,a:aBands?a.balance.percent[i]+'%':'—',b:bBands?b.balance.percent[i]+'%':'—',change:sameBasis?deltaLabel(a.balance.percent[i],b.balance.percent[i],'%p'):'—'}));
 const stableA=stabilityLabel(a),stableB=stabilityLabel(b);
 rows.push({label:'안정감',a:stableA,b:stableB,change:!sameEngine||stableA==='—'||stableB==='—'?'—':stableA===stableB?'같음':stableB+'으로'});
 const paceA=first.pace?.status==='ready'?first.pace.syllablesPerSecond:null,paceB=last.pace?.status==='ready'?last.pace.syllablesPerSecond:null;
 rows.push({label:'빠르기',a:Number.isFinite(paceA)?paceA.toFixed(1):'—',b:Number.isFinite(paceB)?paceB.toFixed(1):'—',change:deltaLabel(paceA,paceB,'',1)});
 const levels={soft:'작게 담김',usable:'잘 담김',loud:'크게 담김',clipped:'소리 잘림'},la=levels[a?.level?.state]||'—',lb=levels[b?.level?.state]||'—';
 rows.push({label:'소리 크기',a:la,b:lb,change:la==='—'||lb==='—'?'—':la===lb?'같음':'달라짐'});
 return rows;
}
function practiceContent(r){
 const working=analysisJobs.has(r.id),ready=r.metrics?.status==='ready';
 if(r.practice?.baselineId){const first=baselineFor(r);if(!first)return '<div class="practice-card"><h2>다시 담은 목소리</h2><p>첫 녹음이 없어 비교할 수 없어요. 이번 녹음은 그대로 남아 있어요.</p></div>';
 const rows=comparisonRows(first,r),old=first.metrics?.method!=='device'||first.metrics?.version<3||first.metrics?.balance&&first.metrics.balance.basis!==BALANCE_BASIS;
 return `<div class="practice-card comparison-card"><div class="comparison-live"><div class="practice-heading"><h2>다시 읽고 달라진 점</h2><span>처음 → 다시</span></div>${working?'<p class="analysis-progress" role="status">비교하고 있어요…</p>':''}<table class="comparison-table"><caption class="sr-only">같은 문장의 첫 녹음과 다시 녹음한 결과</caption><thead><tr><th scope="col">항목</th><th scope="col">처음</th><th scope="col">다시</th><th scope="col">변화</th></tr></thead><tbody>${rows.map(row=>`<tr><th scope="row">${row.band!==undefined?`<i class="band-dot band-${row.band}"></i>`:''}${row.label}</th><td>${esc(row.a)}</td><td class="after-value">${esc(row.b)}</td><td>${esc(row.change)}</td></tr>`).join('')}</tbody></table><p class="comparison-note">빠르기: 음절/초 · %p: 비율의 차이<br>같은 휴대폰·30cm에서 비교해요. 변화가 모두 개선을 뜻하진 않아요.</p>${!analysisJobs.has(first.id)&&(old||first.metrics?.status!=='ready'||first.pace?.status!=='ready')?`<button class="quiet-link" data-analyze="${esc(first.id)}" ${old&&first.metrics?.status==='ready'?'data-acoustic-only="true"':first.metrics?.status==='ready'?'data-pace-only="true"':''}>첫 녹음 ${old?'새 기준으로 분석':'다시 분석'}</button>`:''}${!working&&(!ready||r.pace?.status!=='ready')?`<button class="quiet-link" data-analyze="${esc(r.id)}" ${ready?'data-pace-only="true"':''}>빠진 결과 다시 분석</button>`:''}</div><details class="compare-listen"><summary>처음 목소리 듣기</summary><audio controls preload="none" src="${audioURL(first)}" aria-label="비교할 처음 목소리"></audio></details>${r.practice.tips?.length?`<details class="practice-recap"><summary>연습한 내용</summary>${r.practice.training?.targetHz?`<p>음정 연습 · ${hz(r.practice.training.targetHz)} Hz</p>`:''}${r.practice.training?.mouth?'<p>입모양 · 같은 “아” 소리의 울림 비교</p>':''}${r.practice.tips.map(t=>`<p>${esc(t.action)}</p>`).join('')}</details>`:''}</div>`;
 }
 if(!ready&&working)return '<div class="practice-card"><h2>목소리를 살펴보고 있어요</h2><p role="status">먼저 내 목소리를 들어보세요.</p></div>';
 const tips=coachAdvice(r),goal=goalSettings();
 return `<div class="practice-card"><div class="practice-heading"><h2>다시 읽기 전에</h2><span>진단 · 연습</span></div><ol class="coach-tips">${tips.map(t=>`<li><strong>${esc(t.finding)}</strong><p>${esc(t.action)}</p></li>`).join('')}</ol>${goal.hz&&tips.some(t=>t.finding.startsWith('정한 높이'))?'<button class="quiet-link" data-action="practice-tone">기준음 듣기</button>':''}${!ready?`<button class="quiet-link" data-analyze="${esc(r.id)}">진단 다시 확인</button>`:''}<button class="primary practice-cta" data-practice="${esc(r.id)}">연습하고 다시 읽기 ${icons.arrow}</button><small>첫 녹음과 함께 저장해요.</small></div>`;
}
function practiceMount(r,compact=false){if(!r)return '';const body=`<div class="practice-mount" data-practice-record="${esc(r.id)}" tabindex="-1">${practiceContent(r)}</div>`;return compact?`<details class="practice-history"><summary>${r.practice?.baselineId?'처음과 비교':'진단 · 다시 녹음'}</summary>${body}</details>`:body;}
function readingSentence(){if(!practiceBase)return sentence();const {sentenceId:id,text,title,author,work,section,reference,referenceLabel,sourceUrl,translation,context,source,version}=practiceBase;return {id,text,title,author,work,section,reference,referenceLabel,sourceUrl,translation,context,source,version};}
function startPractice(id){if(recording||starting||busy)return;const base=records.find(r=>r.id===id);if(!base)return;releasePlayback();document.querySelectorAll('audio').forEach(a=>a.pause());practiceBase=base;practicePlan={baselineId:base.id,goal:goalSettings(),tips:coachAdvice(base)};current=base;trainerStart();demo=false;render();window.scrollTo({top:0,behavior:'instant'});$('main').focus({preventScroll:true});}
async function analysisRequest(path,r,controller,timeout){const timer=setTimeout(()=>controller.abort(),timeout);try{const response=await fetch(path,{method:'POST',headers:{'Content-Type':'audio/wav'},body:r.audio,signal:controller.signal});if(!response.ok)throw new Error('analysis');return await response.json();}finally{clearTimeout(timer);}}
async function analyzeRecord(id,paceOnly=false,acousticOnly=false){const r=records.find(x=>x.id===id);if(!r||analysisJobs.has(id))return;const controller=new AbortController();analysisJobs.set(id,controller);refreshVoice(r);const alive=()=>records.includes(r)&&analysisJobs.get(id)===controller&&!controller.signal.aborted;
try{if(!paceOnly||!r.metrics||r.metrics.method!=='device'){r.metrics=await DeviceVoice.analyze(r.audio,controller.signal);if(!alive())return;r.analysisError=false;r.analyzedAt=Date.now();await saveRecord(r);if(!alive())return;refreshVoice(r);}
if(window.BetaAccess&&!await BetaAccess.ensure()){r.pace=r.pace?.status==='ready'?r.pace:{status:'offline'};return;}
if(!alive())return;
if(r.metrics?.status==='ready'){const detail=await analysisRequest('/api/analyze',r,controller,30000);if(!alive())return;if(detail?.status==='ready')r.metrics.formants=detail.formants;await saveRecord(r);refreshVoice(r);if(!acousticOnly){const pace=await analysisRequest('/api/pace',r,controller,180000);if(!alive())return;r.pace=pace;await saveRecord(r);}}
}catch{if(alive()){if(!r.metrics)r.analysisError=true;else if(r.pace?.status!=='ready')r.pace={status:'offline'};}}
finally{if(analysisJobs.get(id)===controller){analysisJobs.delete(id);if(records.includes(r)){await saveRecord(r);refreshVoice(r);}}}}

function cancelAnalysis(id){analysisJobs.get(id)?.abort();analysisJobs.delete(id);}
function classifyPitch(hz,target){if(!Number.isFinite(hz)||!Number.isFinite(target)||hz<=0||target<=0)return 'idle';const cents=1200*Math.log2(hz/target);return Math.abs(cents)<=200?'match':cents>0?'high':'low';}
function resetPitchFeedback(){const edge=$('pitch-edge');if(edge)edge.dataset.state='idle';const text=$('pitch-status');if(text)text.textContent='';}
function updatePitchFeedback(r,rms){const edge=$('pitch-edge');if(!edge)return;if(!r.goal?.hz){resetPitchFeedback();return;}
 const hz=detectLivePitch(r.meter,r.ac.sampleRate),clipped=r.meter.reduce((n,x)=>n+(Math.abs(x)>=.995),0)>r.meter.length*.005;
 if(!hz||clipped){r.pitchHistory=[];r.pitchCandidate=null;r.pitchTicks=0;resetPitchFeedback();return;}
 r.pitchHistory=(r.pitchHistory||[]).concat(hz).slice(-5);if(r.pitchHistory.length<3)return;
 const sorted=[...r.pitchHistory].sort((a,b)=>a-b),median=sorted[Math.floor(sorted.length/2)],next=classifyPitch(median,r.goal.hz);
 if(r.pitchCandidate===next)r.pitchTicks++;else{r.pitchCandidate=next;r.pitchTicks=1;}
 if(r.pitchTicks<3)return;const state=next==='match'?'match':'outside';edge.dataset.state=state;edge.style.setProperty('--pitch-power',Math.min(1,Math.max(.35,rms*12)));
 const text=$('pitch-status'),label=next==='match'?'맞아요':next==='high'?'조금 높아요':'조금 낮아요';if(text&&text.textContent!==label)text.textContent=label;
}
function showVoiceMethod(){openSheet(`<h2>측정 기준</h2><p>기기 분석은 YIN 음높이와 FFT 대역 비중을 사용해요. 안정감은 한 주기 간격의 자기상관(0.60–1.00)을 연습용 막대로 표시해요. Praat의 HNR과 다른 값이며 건강·긴장도 검사가 아니에요. 긴 녹음은 최대 1,000개 구간을 고르게 골라 분석해요. 포먼트와 말의 빠르기는 정밀 분석 연결이 필요해요.</p><p>높이: 소리가 있는 구간의 기본주파수(F0). 음역대: 그중 10–90% 범위예요. 전체로 낼 수 있는 최저·최고음 검사는 아니에요.</p><p>남성 120.8 Hz · 여성 217.1 Hz. 한국 성인 20–39세 120명의 낭독 연구를 참고했어요. 성별을 추정하거나 정상·비정상을 나누지 않아요.</p><a href="https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE00148121" target="_blank" rel="noopener noreferrer">평균 말소리 연구 ↗</a><p>저·중·고음: 100–500 / 500–2,000 / 2,000–5,000 Hz를 비교해요. 원래 강한 저음 쪽 기울기를 6 dB/옥타브로 보정하고, 대역 폭을 맞춘 RMS 강도를 비중으로 바꿔요. 또렷한 목소리 구간을 같은 비중으로 평균해 큰 소리 한 번이 결과를 좌우하지 않게 했어요.</p><p>원래 소리 에너지의 비율이나 인두 사용량은 아니에요. 33%씩이 목표도 아니에요. 100 Hz 아래의 저주파와 5,000 Hz 위의 잡음 영향을 줄였지만, 기종별 마이크 보정을 완료한 값은 아니에요. 같은 휴대폰·30cm·같은 문장으로 비교해주세요.</p><a href="https://praat.org/manual/Source-filter_synthesis_4__Using_existing_sounds.html" target="_blank" rel="noopener noreferrer">음성 기울기 보정 참고 ↗</a><p>배경 잡음과 녹음 기기의 자동 보정은 여전히 영향을 줄 수 있어요.</p><p>포먼트: Praat Burg 방식의 F1·F2·F3 중앙값. 분석 상한은 5,500 Hz예요. 소리 안정감 막대는 HNR 5–25 dB를 흔들림–안정 쪽으로 옮긴 연습용 표시예요. 억양·주변 소음·모음에 영향을 받으며, 근육 긴장이나 건강 판정은 아니에요.</p><a href="https://praat.org/manual/Sound__To_Formant__burg____.html" target="_blank" rel="noopener noreferrer">포먼트 측정 방법 ↗</a><p>소리 크기는 목소리 구간의 녹음 레벨, 강약은 그 레벨의 10–90% 폭을 봐요. 강약 6 dB 미만은 작은 폭으로 안내해요. 스마트폰의 성능이나 실제 음압을 측정한 값은 아니에요. 30cm 거리를 유지하고 비교해요.</p><p>울림 이미지: 포먼트 간격으로 묵직함·담백함·밝음을 임시 분류한 참고예요. 실제 청자의 인상이나 성격을 판정하지 않아요. 문장과 모음이 바뀌면 달라질 수 있어요.</p><p>빠르기: 실제 인식한 한글 음절 ÷ 처음부터 마지막 말까지의 시간. 중간 쉼을 포함해요. 3–5음절/초는 이 앱의 연습 기준이며 정상 범위 판정이 아니에요.</p><p>친절함·신뢰감은 높이 하나로 정해지지 않아요. 두 목표 모두 내가 정한 높이의 ±2반음을 연습 범위로 표시해요. 녹음 중 이 범위 안은 초록빛, 밖은 붉은빛으로 보여줘요. 말하지 않거나 인식이 불확실하면 색을 끕니다.</p><p>${window.BetaAccess?.remote?'기본 분석은 기기에서 해요. 정밀 분석에 연결한 경우에만 녹음을 운영자의 Mac으로 전송해요.':'녹음은 이 컴퓨터에서만 분석해요.'} 분석 서버에는 파일을 남기지 않아요.</p>`);}
function showVoiceGoal(){const g=goalSettings(),latest=records.find(r=>r.metrics?.status==='ready'),base=g.hz||Math.round(latest?.metrics.pitchMedian||0);openSheet(`<h2>목소리 목표</h2><p>내가 편하게 낼 수 있는 높이로 정해요.</p><form id="voice-goal-form"><div class="goal-directions"><label><input type="radio" name="direction" value="friendly" ${g.kind==='friendly'?'checked':''}>친절한 말투</label><label><input type="radio" name="direction" value="trust" ${g.kind==='trust'?'checked':''}>신뢰감 있는 말투</label></div><label class="goal-height" for="goal-hz">기준 높이 <input id="goal-hz" name="hz" type="number" min="65" max="450" step="1" required value="${base||''}" placeholder="예: 150"> Hz</label><p>말투의 정답 음정은 없어요. 한 번 정하면 다음에도 유지돼요.</p><button type="button" class="quiet-link" data-action="goal-tone">이 높이 듣기</button><button class="primary" type="submit">저장</button></form>`);}
async function playGoalTone(frequency=null){if(frequency===null){const input=$('goal-hz');if(!input?.reportValidity())return;frequency=Number(input.value);}if(!Number.isFinite(frequency)||frequency<65||frequency>450)return;releasePlayback();document.querySelectorAll('audio').forEach(a=>a.pause());const ac=new (window.AudioContext||window.webkitAudioContext)();try{await ac.resume();const osc=ac.createOscillator(),gain=ac.createGain(),now=ac.currentTime;osc.frequency.value=frequency;gain.gain.setValueAtTime(0,now);gain.gain.linearRampToValueAtTime(.08,now+.08);gain.gain.setValueAtTime(.08,now+.8);gain.gain.linearRampToValueAtTime(0,now+1);osc.connect(gain);gain.connect(ac.destination);osc.onended=()=>ac.close();osc.start();osc.stop(now+1.05);}catch{await ac.close();toast('소리를 재생하지 못했어요.');}}

// Live YIN reused from SEMI / Touching Voice. No recognition during playback.
function detectLivePitch(input,sampleRate){const step=Math.max(1,Math.floor(sampleRate/8000)),rate=sampleRate/step,n=Math.floor(input.length/step),x=new Float32Array(n);let mean=0,power=0;for(let i=0;i<n;i++){let sum=0;for(let j=0;j<step;j++)sum+=input[i*step+j];x[i]=sum/step;mean+=x[i];}mean/=n;for(let i=0;i<n;i++){x[i]-=mean;power+=x[i]*x[i];}if(Math.sqrt(power/n)<.006)return null;const lo=Math.floor(rate/800),hi=Math.ceil(rate/65),w=Math.min(384,n-hi-2);if(w<160)return null;const d=new Float32Array(hi+2);for(let t=1;t<=hi+1;t++){let sum=0;for(let j=0;j<w;j++){const a=x[j]-x[j+t];sum+=a*a;}d[t]=sum;}let run=0;d[0]=1;for(let t=1;t<=hi+1;t++){run+=d[t];d[t]=run?d[t]*t/run:1;}let best=-1;for(let t=lo;t<=hi;t++){if(d[t]<.15){while(t<hi&&d[t+1]<d[t])t++;best=t;break;}}if(best<0)return null;const a=d[best-1],b=d[best],z=d[best+1],den=a-2*b+z,hz=rate/(best+(den?.5*(a-z)/den:0));return hz>=65&&hz<=800?hz:null;}

document.addEventListener('click',async e=>{if(e.target.closest('[data-action="connect-analysis"]')&&await window.BetaAccess?.connect()){for(const r of records.filter(r=>r.id===current?.id||document.querySelector(`[data-voice-record="${r.id}"]`)))analyzeRecord(r.id,true);}});

window.addEventListener('beta-connected',()=>{if(current)analyzeRecord(current.id,true);});
